export { default as Navbar } from "./navbar";
export { default as Home } from "./home";
export { default as Statistics } from "./statistics";
export { default as Contract } from "./contract";
export { default as Billing } from "./billing";
export { default as Business } from "./business";
export { default as FeatureCard } from "./feature-card";
export { default as CTA } from "./cta";
export { default as Tastimonials } from "./testimonials";
export { default as FeedbackCard } from "./feedback-card";
export { default as Client } from "./client";
export {default as ClientCard } from "./client-card";
